# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET App Build

env:
  registryName: mattrdevopsreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: Application/src/RazorPagesTestSample
  tag: ${{ github.run_number }}

on:
  push:
    branches: [ "main" ]
    paths: Application/**
  pull_request:
    branches: [ "main" ]
    paths: Application/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
      #Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Logon
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.registryName }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        
      - name: Docker Build
        run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath

      - name: Docker Push
        run: docker push $registryName/$repositoryName:$tag

  deploy-on-dev:
    runs-on: ubuntu-latest
    needs: docker-build-push
    environment: 
      name: dev
      url: https://mattr-dev.azurewebsites.net
    steps:
      - name: Checking Out
        uses: actions/checkout@v3

      - name: AzLogin
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZ_CREDENTIALS }}

      - name: Azure WebApp Deploy on $environment
        uses: azure/webapps-deploy@v2
        with: 
          app-name: mattr-test
          images: ${{env.registryName}}/${{env.repositoryName}}:${{env.tag}}
      - name: Azure Logout
        run: az logout


#The .csproj project file is located in 
#./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
#The .csproj test file is located in 
#./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj
#